### ISSUE TITLE
Reduce unnecessary docker image builds

### ISSUE THREAD

**Issue by pameladelgado** [SwissDataScienceCenter/renku-project-template#57] opened 2020-02-28 21:13 UTC
**Description**

At the moment the CI/CD in the projects is configured in such a way that the docker image is built for every single commit. This is not only unnecessary most of the times but it also slows down the time a user has to wait to start an environment, even for the simplest of changes. On the other hand, gitlab-runner resources are occupied.

**Proposal**

A docker image should be built by default when only selected files are modified: Dockerfile, requirements.txt, environment.yaml.

**Comment by rokroskar** [comment] 2020-02-28 21:22
duplicate of https://github.com/SwissDataScienceCenter/renku/issues/476 - it's easy to do this in the CI, but it needs some additional support in order for the UI to operate properly so it isn't a simple change. I'm closing this in favor of the existing issue, but I agree that it should be done!

**Closed by rokroskar** 2020-02-28 21:22 UTC
Labels: QA
